### PR TITLE
firebase & router post

### PR DESCRIPTION
**Pull request by nathanharper**

### CODE REVIEW

**Comment by nathanharper** [comment]
:bowtie:

**Comment by nathanharper** [comment]
should have a good one on flux later today/tomorrow

**Comment by dirkkelly** [comment]
:+1: Aww yeah. Very interested to see the router, I spent a lot of time working with the ember one back in the day. The JSX syntax is a shame on there, seems cosmetic enough that it could evolve over time. There's convergence happening on both projects, creating better base expectations.

**Comment by dirkkelly** [comment]
https://blog.interexchange.org/engineering/2015/03/10/react-griddle/

**Pull request closed without merging**
